import type { ApiSchemas } from './api'

export type CourseCreate = ApiSchemas['CourseCreate']
export type CourseTaskView = ApiSchemas['CourseTaskView']
export type CourseSource = ApiSchemas['TeachSource']
export type CourseMission = ApiSchemas['TeachMission']
export type CourseLessonSummary = ApiSchemas['CourseLessonSummary']
export type CourseView = ApiSchemas['CourseView']
export type CourseList = ApiSchemas['CourseList']
export type CourseOutlineUpdate = ApiSchemas['CourseOutlineUpdate']
export type CourseQuizCreate = ApiSchemas['CourseQuizCreate']
export type CourseQuizLinkView = ApiSchemas['CourseQuizLinkView']
export type CourseLessonView = ApiSchemas['CourseLessonView']
export type CourseEvidenceView = ApiSchemas['CourseEvidenceView']
export type CourseNextAction = ApiSchemas['CourseNextAction']
export type CourseWeakPoint = ApiSchemas['CourseWeakPoint']
export type CourseProgressView = ApiSchemas['CourseProgressView']
export type CourseSourcePolicy = CourseView['source_policy']
export type CourseStatus = CourseView['status']
export type CourseLessonStatus = CourseLessonView['status']
