import type { ApiSchemas } from './api'

export type PracticeSpec = ApiSchemas['PracticeSpec']
export type Practice = ApiSchemas['PracticeView']
export type PracticeTask = ApiSchemas['PracticeTaskView']
export type PracticeQuestion = NonNullable<Practice['questions']>[number]
export type PracticeAnswer = ApiSchemas['PracticeAnswerBody']['answer']
export type PracticeAnswerBody = ApiSchemas['PracticeAnswerBody']
export type PracticeReceipt = ApiSchemas['PracticeSubmissionReceipt']
export type PracticeCompletion = ApiSchemas['PracticeCompletionReceipt']
export type PracticeAttempt = ApiSchemas['PracticeAttemptView']
export type PracticeAssessment = ApiSchemas['PracticeAssessmentView']
export type ReviewPracticeBody = ApiSchemas['ReviewPracticeBody']
export type PracticeEvidence = ApiSchemas['PublicPracticeEvidence']
export type PracticeCost = ApiSchemas['PracticeCostPreview']
export type PracticeHelp = ApiSchemas['PracticeHelpView']
export type PracticeReviewContext = ApiSchemas['PracticeReviewContext']
export type PracticeReviewBody = ApiSchemas['PracticeReviewBody']
export type PracticeAssessmentRef = ApiSchemas['AssessmentRef']
export type PracticeSelfReviewBody = ApiSchemas['PracticeSelfReviewBody']
export type PracticeSelfReviewReceipt = ApiSchemas['PracticeSelfReviewReceipt']
