CREATE TABLE IF NOT EXISTS learning_courses (
 course_id VARCHAR(64) PRIMARY KEY, owner_id BIGINT UNSIGNED NOT NULL,
 spec_json JSON NULL, source_policy VARCHAR(24) NOT NULL,
 requested_scope_json JSON NULL, resolved_scope_json JSON NULL,
 scope_fingerprint CHAR(64) NOT NULL,
 outline_json JSON NULL, evidence_json JSON NULL,
 creation_task_id VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL,
 outline_task_id VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL,
 active_task_id VARCHAR(64) COLLATE utf8mb4_unicode_ci NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'generating', revision INT NOT NULL DEFAULT 1,
 skill_version VARCHAR(64) NULL, skill_hash CHAR(64) NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 UNIQUE KEY uk_course_owner (course_id,owner_id),
 UNIQUE KEY uk_course_creation_task (creation_task_id),
 KEY idx_course_owner_updated (owner_id,updated_at),
 FOREIGN KEY (owner_id) REFERENCES users(id),
 FOREIGN KEY (creation_task_id,owner_id) REFERENCES quiz_tasks(task_id,user_id),
 FOREIGN KEY (outline_task_id,owner_id) REFERENCES quiz_tasks(task_id,user_id),
 FOREIGN KEY (active_task_id,owner_id) REFERENCES quiz_tasks(task_id,user_id),
 CONSTRAINT ck_course_policy CHECK (source_policy IN ('topic','strict_docs')),
 CONSTRAINT ck_course_status CHECK (status IN ('generating','ready','partial','failed','cancelled','source_revoked')),
 CONSTRAINT ck_course_revision CHECK (revision >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS learning_course_lessons (
 lesson_id VARCHAR(64) PRIMARY KEY, course_id VARCHAR(64) NOT NULL,
 owner_id BIGINT UNSIGNED NOT NULL, unit_ref VARCHAR(80) NOT NULL, position INT NOT NULL,
 unit_json JSON NULL, content_json JSON NULL, evidence_json JSON NULL,
 content_version INT NOT NULL DEFAULT 0,
 generation_task_id VARCHAR(64) COLLATE utf8mb4_unicode_ci NULL,
 active_task_id VARCHAR(64) COLLATE utf8mb4_unicode_ci NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'not_generated',
 read_at DATETIME(6) NULL, last_opened_at DATETIME(6) NULL,
 revision INT NOT NULL DEFAULT 1,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 UNIQUE KEY uk_course_lesson_owner (lesson_id,owner_id),
 UNIQUE KEY uk_course_lesson_course_owner (lesson_id,course_id,owner_id),
 UNIQUE KEY uk_course_lesson_ref (course_id,unit_ref),
 UNIQUE KEY uk_course_lesson_position (course_id,position),
 FOREIGN KEY (course_id,owner_id) REFERENCES learning_courses(course_id,owner_id),
 FOREIGN KEY (generation_task_id,owner_id) REFERENCES quiz_tasks(task_id,user_id),
 FOREIGN KEY (active_task_id,owner_id) REFERENCES quiz_tasks(task_id,user_id),
 CONSTRAINT ck_course_lesson_status CHECK (status IN ('not_generated','generating','ready','material_gap','failed','cancelled','source_revoked')),
 CONSTRAINT ck_course_lesson_position CHECK (position >= 0),
 CONSTRAINT ck_course_lesson_revision CHECK (revision >= 1 AND content_version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS learning_course_quiz_links (
 link_id VARCHAR(64) PRIMARY KEY, course_id VARCHAR(64) NOT NULL,
 lesson_id VARCHAR(64) NOT NULL, owner_id BIGINT UNSIGNED NOT NULL,
 task_id VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL,
 kind VARCHAR(16) NOT NULL, parent_link_id VARCHAR(64) NULL,
 content_version INT NOT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 UNIQUE KEY uk_course_quiz_task (task_id,owner_id),
 UNIQUE KEY uk_course_quiz_parent_owner (link_id,lesson_id,owner_id),
 KEY idx_course_quiz_lesson (lesson_id,created_at),
 FOREIGN KEY (lesson_id,course_id,owner_id) REFERENCES learning_course_lessons(lesson_id,course_id,owner_id),
 FOREIGN KEY (task_id,owner_id) REFERENCES quiz_tasks(task_id,user_id),
 FOREIGN KEY (parent_link_id,lesson_id,owner_id) REFERENCES learning_course_quiz_links(link_id,lesson_id,owner_id),
 CONSTRAINT ck_course_quiz_kind CHECK (kind IN ('initial','review')),
 CONSTRAINT ck_course_quiz_version CHECK (content_version >= 1),
 CONSTRAINT ck_course_quiz_parent CHECK ((kind='initial' AND parent_link_id IS NULL) OR (kind='review' AND parent_link_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
