CREATE TABLE IF NOT EXISTS learning_course_tutor_turns (
 turn_id VARCHAR(64) PRIMARY KEY,
 course_id VARCHAR(64) NOT NULL, lesson_id VARCHAR(64) NOT NULL,
 owner_id BIGINT UNSIGNED NOT NULL, content_version INT NOT NULL,
 mode VARCHAR(16) NOT NULL, block_index INT NULL,
 question TEXT NULL, check_attempt_id VARCHAR(64) NULL,
 creation_task_id VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL,
 last_task_id VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL,
 active_task_id VARCHAR(64) COLLATE utf8mb4_unicode_ci NULL,
 active_content_version INT GENERATED ALWAYS AS
  (CASE WHEN active_task_id IS NOT NULL THEN content_version ELSE NULL END) STORED,
 response_json JSON NULL, evidence_json JSON NULL,
 skill_version VARCHAR(64) NULL, skill_hash CHAR(64) NULL,
 revoked_at DATETIME(6) NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 UNIQUE KEY uk_course_tutor_owner (turn_id,owner_id),
 UNIQUE KEY uk_course_tutor_creation_task (creation_task_id,owner_id),
 UNIQUE KEY uk_course_tutor_last_task (last_task_id,owner_id),
 UNIQUE KEY uk_course_tutor_active_version (owner_id,lesson_id,active_content_version),
 KEY idx_course_tutor_history (owner_id,lesson_id,content_version,created_at),
 KEY idx_course_tutor_check (check_attempt_id,lesson_id,course_id,owner_id,content_version),
 FOREIGN KEY (course_id,owner_id) REFERENCES learning_courses(course_id,owner_id),
 FOREIGN KEY (lesson_id,course_id,owner_id) REFERENCES learning_course_lessons(lesson_id,course_id,owner_id),
 FOREIGN KEY (creation_task_id,owner_id) REFERENCES quiz_tasks(task_id,user_id),
 FOREIGN KEY (last_task_id,owner_id) REFERENCES quiz_tasks(task_id,user_id),
 FOREIGN KEY (active_task_id,owner_id) REFERENCES quiz_tasks(task_id,user_id),
 CONSTRAINT ck_course_tutor_mode CHECK (mode IN ('explain','example','hint','check')),
 CONSTRAINT ck_course_tutor_version CHECK (content_version >= 1),
 CONSTRAINT ck_course_tutor_block CHECK (block_index IS NULL OR block_index >= 0),
 CONSTRAINT ck_course_tutor_check CHECK
  ((mode='check' AND check_attempt_id IS NOT NULL) OR (mode<>'check' AND check_attempt_id IS NULL)),
 CONSTRAINT ck_course_tutor_active CHECK (active_task_id IS NULL OR active_task_id=last_task_id),
 CONSTRAINT ck_course_tutor_published CHECK (response_json IS NULL OR active_task_id IS NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
