"""Controlled one-factor experiments and pre-ablation frozen-run compatibility."""

import json
from types import SimpleNamespace

import pytest

from app.rag.contracts import PipelineConfig


# Captured before adding the ablation strategy field. These are historical wire
# values and digests, not values regenerated by the implementation under test.
FROZEN_DEFAULT = {
    "pipeline_version": "rag-v1",
    "index_profile_id": "legacy-char-v1",
    "index_profile_hash": None,
    "retriever": "hybrid",
    "dense_top_k": 20,
    "lexical_top_k": 20,
    "rrf_k": 60,
    "candidate_limit": 40,
    "final_top_k": 8,
    "max_subqueries": 3,
    "max_retrieval_rounds": 2,
    "max_generation_attempts": 2,
    "max_llm_calls": 5,
    "context_token_budget": 6000,
    "model_context_window": 32768,
    "output_token_reserve": 4096,
    "prompt_version": "evidence-quiz-v1",
    "generator_model": "configured",
    "legacy_source_archive_sha256": None,
    "legacy_source_commit": None,
    "parent_expansion": False,
    "require_semantic_validation": True,
    "reranker": {
        "provider": "none",
        "model_revision": None,
        "license": None,
        "endpoint": None,
        "timeout_seconds": 10.0,
        "allow_rrf_fallback": False,
    },
}

FROZEN_CASES = [
    ("rag-v1", {}, "58c973501bda75a8d5d56753b0fc859c38277875c5fc7e7f0830ec738997795d"),
    (
        "legacy-summary-b0",
        {
            "retriever": "legacy_dense",
            "dense_top_k": 4,
            "final_top_k": 4,
            "require_semantic_validation": False,
            "legacy_source_archive_sha256": "a" * 64,
            "legacy_source_commit": "7302ad2",
        },
        "a73590e6fb8db64b533d842e188ce5df598e6dc01da5f69ba404c47ebcb7a4e0",
    ),
    (
        "legacy-dense-v1",
        {"retriever": "legacy_dense"},
        "460a219639d3632610cdb3ee707fc00247d8d5079775385278766c8de9dc1046",
    ),
    (
        "llamaindex-dense-v1",
        {"retriever": "llamaindex_dense"},
        "2195ca8350e7400b347cee5e7ffe9239bc3ca3768aa0805850c5856ddd17f66c",
    ),
    (
        "bm25-v1",
        {"retriever": "bm25"},
        "1f7b490995d32e171bda5d701e4efff6fbec9600fb9f0389b907103131c4c8b9",
    ),
    (
        "hybrid-v1",
        {},
        "ff1ea77bf06a5b246c6373a4090e681b542f73920f926267181dcf4b82423433",
    ),
    (
        "hybrid-rerank-v1",
        {
            "reranker": {
                "provider": "bge-v2-m3",
                "model_revision": "fixture-v1",
                "license": "test-only",
                "endpoint": "http://127.0.0.1:8001/rerank",
                "timeout_seconds": 10.0,
                "allow_rrf_fallback": False,
            }
        },
        "3f81447ec1c4f295ae44cdbae33eebd94b8358dad97e029260611ebb24bfbb59",
    ),
    (
        "structure-v1",
        {"index_profile_id": "structure-token-v1", "parent_expansion": True},
        "03d41e5f73a1f62831ec58017146abe5bd59c4be36b438374aa29b015e334e70",
    ),
]

ABLATION_IDS = [
    "ablation-char-v1",
    "ablation-structure-v1",
    "ablation-parent-v1",
    "ablation-coverage-v1",
]


@pytest.mark.parametrize("identifier,changes,frozen_hash", FROZEN_CASES)
def test_pre_ablation_frozen_payload_and_hash_are_unchanged(
    identifier, changes, frozen_hash
):
    from app.rag.contracts import IndexProfile, PipelineManifest
    from app.rag.registry import get_pipeline_config

    payload = {**FROZEN_DEFAULT, "pipeline_version": identifier, **changes}
    restored = PipelineConfig.model_validate(json.loads(json.dumps(payload)))
    assert restored.pipeline_config_hash == frozen_hash
    assert restored.model_dump(mode="json") == payload
    assert json.loads(restored.model_dump_json()) == payload
    manifest = PipelineManifest(
        pipeline_config_hash=frozen_hash,
        code_hash="old-code",
        dependency_hash="old-lock",
        config=restored,
        index_profile=IndexProfile(),
        parser_version="old-parser",
        normalizer_version="old-normalizer",
    )
    assert manifest.model_dump(mode="json")["config"] == payload
    configured = (
        PipelineConfig()
        if identifier == "rag-v1"
        else get_pipeline_config(identifier, **changes)
    )
    assert configured.pipeline_config_hash == frozen_hash


def test_ablation_profiles_change_one_factor_and_are_publicly_selectable():
    from app.rag.registry import get_pipeline_config
    from app.services.evaluation_service import list_pipelines

    configs = [get_pipeline_config(identifier) for identifier in ABLATION_IDS]
    for before, after, factor in zip(
        configs,
        configs[1:],
        ["index_profile_id", "parent_expansion", "coverage_strategy"],
    ):
        previous, candidate = (
            before.model_dump(mode="json"),
            after.model_dump(mode="json"),
        )
        changes = {
            key
            for key in previous.keys() | candidate.keys()
            if previous.get(key) != candidate.get(key)
        }
        assert changes == {"pipeline_version", factor}
        assert before.pipeline_config_hash != after.pipeline_config_hash
    for config in configs:
        assert config.context_token_budget == 6000
        assert (
            config.dense_top_k,
            config.lexical_top_k,
            config.candidate_limit,
            config.final_top_k,
        ) == (20, 20, 40, 8)
        assert config.require_semantic_validation and config.max_llm_calls == 5
        assert config.reranker.provider == "none"
        assert (
            PipelineConfig.model_validate_json(
                config.model_dump_json()
            ).pipeline_config_hash
            == config.pipeline_config_hash
        )
    published = {
        item["pipeline_id"]: item["config"] for item in list_pipelines()["items"]
    }
    assert set(ABLATION_IDS) <= published.keys()
    assert published[ABLATION_IDS[0]]["coverage_strategy"] == "single-goal-v1"
    assert published[ABLATION_IDS[-1]]["coverage_strategy"] == "catalog-v1"


def test_explicit_coverage_strategy_changes_fingerprint_without_rewriting_old_config():
    legacy = PipelineConfig.model_validate(FROZEN_DEFAULT)
    single = PipelineConfig.model_validate(
        {**FROZEN_DEFAULT, "coverage_strategy": "single-goal-v1"}
    )
    catalog = PipelineConfig.model_validate(
        {**FROZEN_DEFAULT, "coverage_strategy": "catalog-v1"}
    )
    assert (
        len({config.pipeline_config_hash for config in (legacy, single, catalog)}) == 3
    )
    assert "coverage_strategy" not in legacy.model_dump(mode="json")
    assert single.model_dump(mode="json")["coverage_strategy"] == "single-goal-v1"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "identifier,expected_targets",
    [("ablation-structure-v1", 1), ("ablation-coverage-v1", 2), ("hybrid-v1", 2)],
)
async def test_ablation_executes_frozen_coverage_strategy_and_preserves_evidence(
    identifier, expected_targets
):
    from app.rag.contracts import RetrievalResult, ValidationResult
    from app.rag.pipeline import PipelinePorts, generate_quiz_artifact
    from app.rag.registry import get_pipeline_config
    from app.rag.scope import normalize_spec
    from tests.rag.test_artifact_pipeline import context_and_scope, quiz_for

    original, actor, context, scope = context_and_scope()
    catalog = {
        "doc_1": [
            SimpleNamespace(section_id="light", title="光照"),
            SimpleNamespace(section_id="growth", title="生长"),
        ]
    }
    evidence = [
        original.model_copy(
            update={
                "evidence_id": "ev_" + section,
                "chunk_id": "chunk_" + section,
                "locator": original.locator.model_copy(
                    update={
                        "section_id": section,
                        "section_ids": [section],
                        "start_char": index * 9,
                        "end_char": index * 9 + 8,
                    }
                ),
            }
        )
        for index, section in enumerate(("light", "growth"))
    ]
    requested_queries = []

    async def retrieve(query, *args, **kwargs):
        requested_queries.append(query)
        return RetrievalResult(evidence=evidence, candidates=evidence)

    async def generate(spec, pack, coverage, attempt, feedback=None):
        payload = quiz_for(spec, pack, coverage)
        targets = [
            target for target in coverage.targets for _ in range(target.question_quota)
        ]
        for question, target in zip(payload["questions"], targets):
            question["coverage_target_id"] = target.target_id
            question["citation_refs"] = [target.evidence_ids[0]]
        return payload

    async def validate(*args):
        return ValidationResult(passed=True, semantic_status="passed")

    async def authorize(current):
        assert current.fingerprint == scope.fingerprint
        return current

    config = get_pipeline_config(identifier)
    # Simulate the owner reading the already-frozen JSON; registry defaults are
    # not consulted during execution of an existing evaluation run.
    restored = PipelineConfig.model_validate_json(config.model_dump_json())
    artifact = await generate_quiz_artifact(
        normalize_spec(
            {"user_input": "完整学习", "doc_id": "doc_1", "question_count": 3}
        ),
        actor,
        context,
        PipelinePorts(
            retrieve=retrieve,
            generate=generate,
            reauthorize=authorize,
            semantic_validator=validate,
            catalog=catalog,
        ),
        resolved_scope=scope,
        config=restored,
    )
    assert requested_queries == (
        ["完整学习"] if expected_targets == 1 else ["完整学习 光照", "完整学习 生长"]
    )
    assert len(artifact.evidence_pack.coverage.targets) == expected_targets
    assert artifact.pipeline_config_hash == config.pipeline_config_hash
    assert artifact.effective_config["pipeline"] == config.model_dump(mode="json")
    assert artifact.usage.llm_calls == 2
    assert len(artifact.questions) == 3
    assert all(
        set(question.citation_refs) <= set(artifact.evidence_pack.provided_evidence_ids)
        for question in artifact.questions
    )


@pytest.mark.asyncio
async def test_parent_ablation_retrieves_persisted_parents_from_the_same_build(
    tmp_path,
):
    from app.rag.artifact_store import OwnerIndexStore
    from app.rag.engine import RagEngine
    from app.rag.registry import get_index_profile, get_pipeline_config
    from tests.rag.helpers import FixtureEmbedding, request_for, scope_for

    async def authorize(scope):
        return scope

    profile = get_index_profile(
        "structure-token-v1",
        embedding_model="fixture-vector-v1",
        embedding_dimensions=3,
    )
    request = request_for(
        tmp_path,
        text="# 光照\n" + "光合作用需要光，并将光能转换为化学能。" * 40,
        profile=profile,
    )
    with OwnerIndexStore(tmp_path / "data", process_role="rag_owner") as store:
        engine = RagEngine(store, FixtureEmbedding(), reauthorize=authorize)
        built = await engine.build(request)
        scope = scope_for(built)
        child = await engine.retrieve(
            "光照", scope, get_pipeline_config("ablation-structure-v1")
        )
        parent = await engine.retrieve(
            "光照", scope, get_pipeline_config("ablation-parent-v1")
        )
        children = {node.node_id for node in built.nodes if not node.is_parent}
        parents = {node.node_id for node in built.nodes if node.is_parent}
        assert child.evidence and parent.evidence
        assert {item.chunk_id for item in child.evidence} <= children
        assert {item.chunk_id for item in parent.evidence} <= parents
        assert {item.index_build_id for item in child.evidence + parent.evidence} == {
            built.index_build_id
        }
        assert child.candidates == parent.candidates
